# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afbdd05fe4447563ba79e08c2ce574616b77c0298b64565e8513abe8f0fa190faac11fc346f9c4908292b139673b02628c97c829ddf9558930fd01bc5bd7d0ea

test:
  secret_key_base: e4aedff3a3bd2da0231c6ace745f73539c3ffe1a4c1c362c986b182cdc15cf02f4469a0f003800058459523892631427b161a8b21f3683da48f72e2e9cecd9a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
